### ISSUE TITLE
GridItems jump when one is removed

### ISSUE THREAD

**Issue by Style87** [cuire/svelte-grid-extended#102]
I have a number of items rendered to the grid. When removing one from the array the items at higher indexes all move to the position of the element below them and then back to their correct position.

Notice when 6 is removed 7 moves to 6, 8 moves to 7 and then both 7 and 8 slide back to their correct unchanged positions.
https://svelte.dev/playground/b927483007d2483abfbf3f79718e08ae?version=4.1.1

Am I doing something wrong? Is this a bug? I would expect items not changed in the data array to be unchanged in the UI.

**Comment by cuire** [comment]
Hi. That is how [each loop are working in svelte](https://svelte.dev/docs/svelte/each#Keyed-each-blocks). You can simply change line 24:
```
+ {#each items as item (item.id)}
- {#each items as item}
```

And that will resolve your issue
