### ISSUE TITLE
[Feature] Support stores

### ISSUE THREAD

**Issue by joakim** [cuire/svelte-grid-extended#20]
I have a store that's an array of objects representing items in the grid.

It would be really nice to be able to do just this and have the grid reflect any changes reactively:

```svelte
<script>
  import Thing from './Thing.svelte'
  import { things } from '../stores/things'
  let items = derived(things, mapThingsToItems)
</script>

<Grid {items} cols={10} rows={10} let:item>
  <Thing data={item.data} />
</Grid>
```

**Comment by cuire** [comment]
@joakim, I think you will find it useful, that you can also bind the store to items, so the grid component updates store value, when grid changes. 
https://svelte.dev/repl/7a08b5f150dc432480ae321147324d43?version=3.55.1

**Comment by joakim** [comment]
Thanks, @cuire! It's exactly what I was working on, so that was very useful :)
