### ISSUE TITLE
[Feature] New API

### ISSUE THREAD

**Issue by cuire** [cuire/svelte-grid-extended#23]
I want to change plugin api. The current version creates too many restrictions and is not intuitive in many ways.
My plan is to something like this:
```svelte
<Grid cols={10} rows={10}>
	<GridItem x={0} y={0}>Content<GridItem />
	<GridItem x={1} y={1}>Content<GridItem />
	<GridItem>{ /* somehow calc insert position */}<GridItem />
</Grid>
```
This will allow users to control the creation of the grid themselves. This approach opens up many possibilities for customization, for example, custom logic for moving a single cell and much more.

Also, this approach will allow you to use slots for modifications (#21).

```svelte
<Grid cols={10} rows={10}>
	<GridItem x={0} y={0}>
		<div slot="dragHandle">Drag Me</div>
		<p>Content</p>
	<GridItem />
</Grid>
```

I will probably start working on it in 2 weeks. Stay tuned 💖

**Comment by fabiot21** [comment]
Hi @cuire! is this still in dev? I'm asking so to build some features in the near future on top of this new API.

**Comment by cuire** [comment]
> Hi @cuire! is this still in dev? I'm asking so to build some features in the near future on top of this new API.

Hello, new API is almost done. I have a blockage at work, as soon as I figure it out, I will publish a pr

**Comment by multiplehats** [comment]
Looking forward to this :)!

**Comment by secondme2** [comment]
Hey @cuire! Foremost, thank you so much for this amazing library. Just wanted to ask: are you still planning on adding this new API? Is the library still maintained/supported?

**Comment by cuire** [comment]
Done in 1.0.0

**Comment by secondme2** [comment]
You're the best @cuire
