### ISSUE TITLE
Error in repl

### ISSUE THREAD

**Issue by fabiot21** [cuire/svelte-grid-extended#29]
After version 0.3 when i try to run [repl](https://svelte.dev/repl/527ef09f35cd4d7094cd6cf38bcf822d?version=4.0.4) is now throwing error `"Cannot import "svelte-grid-extended": could not find entry point in "undefined/package.json"."`

**Comment by fabiot21** [comment]
Addition info:

if I change the import to `import Grid from 'svelte-grid-extended@0.2';` works correctly

**Comment by cuire** [comment]
Sorry for that, I published the package incorrectly. Now it should work fine. Ty for reporting that 🖤
