### ISSUE TITLE
[Bug] collision true. Can't move element to some coordinates

### ISSUE THREAD

**Issue by fabiot21** [cuire/svelte-grid-extended#30]
When collision is active, when trying to move an element it can only be moved to certain spaces not everywhere.

Reproduction: Can't drag on this [repl](https://svelte.dev/repl/527ef09f35cd4d7094cd6cf38bcf822d?version=4.0.4) element "0" down (y axis). Only works if collision is false.

<img width="1728" alt="Screenshot 2023-07-11 at 15 23 58" src="https://github.com/cuire/svelte-grid-extended/assets/11488162/7146f236-f392-4824-b10e-93e916cfdc7e">

**Comment by hearthole** [comment]
It is intended. without the y-axis compression, it's hard to decide where collision target will be moved. plz refer to change log https://github.com/cuire/svelte-grid-extended/pull/27#issue-1785173048

**Comment by cuire** [comment]
Check #32
