### ISSUE TITLE
[Feature Request] Helper to get available position

### ISSUE THREAD

**Issue by fabiot21** [cuire/svelte-grid-extended#38]
Add an utility or helper class that can return an available position within the grid given a new potential item (only `w` and `h`) and current items. This helper could provide the `x` and `y` coordinates where the new item can be placed within the items.

The function could be based on `getAvailablePosition`

**Comment by fabiot21** [comment]
(this class could be extended to have more utility functions)

**Comment by cuire** [comment]
Maybe something like this
```svelte
<Grid {...} let:controller={gridController} />
```

**Comment by fabiot21** [comment]
what about `bind:controller={gridController}` or `import { gridController } from '$lib'`? to have a reference outside the `Grid` component
