### ISSUE TITLE
The compress method is missing from the grid controller

### ISSUE THREAD

**Issue by gitryder** [cuire/svelte-grid-extended#79]
According to the documentation, there is supposed to be a `compress` method available on the grid controller. However, upon attempting to use it in a real-world scenario, it appears that the compress method is not actually present on the grid controller object.

### Version Information:

Library Version: 1.1.4
Reproducible Example: [Repl link](https://svelte.dev/repl/79bcc70f11944d9e9b03970de731b3e2?version=4.2.11)

### Steps to Reproduce:

1. Use the latest version (1.1.4) of svelte-grid-extended.
2. Attempt to access the `compress` method on the grid controller object.

### Expected Behavior:
The `compress` method should be available and functional as described in the documentation.

### Actual Behavior:
The `compress` method is not available on the grid controller object, leading to errors or unexpected behavior when attempting to use it.

**Comment by cuire** [comment]
Hey. Fixed in v1.2.0 🩷
